Config = {}

Config.EnabledByDefault = true
Config.AllowToggleCommand = false
Config.ToggleCommand = 'bodycam'
Config.HudEnabled = true
Config.HideReticle = true
Config.FirstPersonFov = 78.0
Config.CameraOffset = vector3(0.0, 0.0, 0.08)
Config.VehicleCameraOffset = vector3(0.0, 0.0, 0.02)
Config.EnforceInterval = 250
Config.HudUpdateInterval = 100
Config.CameraSway = true
Config.BreathingAmount = 0.018
Config.WalkShakeAmount = 0.012
Config.RunShakeAmount = 0.028
Config.VehicleShakeAmount = 0.008
Config.HudNoise = true
Config.ShowVehicleSpeed = true
Config.ShowStreet = true
Config.ShowUnitId = true
Config.UnitIdPrefix = 'UNIT'
Config.HudTitle = 'BODYCAM'
Config.HudColor = '#b8ff48'
